package Compras.ZafCom01;







/*
 * ZafCom01_01.java
 *
 * Created on 27 de marzo de 2006, 12:15
 */



import Librerias.ZafParSis.ZafParSis;
import Librerias.ZafUtil.ZafUtil;
import Librerias.ZafColNumerada.ZafColNumerada;
import Librerias.ZafTblUti.ZafTblMod.ZafTblMod;
import Librerias.ZafTblUti.ZafTblEdi.ZafTblEdi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
/**
 *
 * @author  jayapata
 */
public class ZafCom01_01 extends javax.swing.JDialog {
    
    //Constantes: Columnas del JTable:
    final int INT_TBL_DAT_LIN=0;                        //Línea
    final int INT_TBL_DAT_COD_DOC=1;                    //Código del documento.
    final int INT_TBL_DAT_NUM_COT=2;                    //Numero de Cotizacion.
    final int INT_TBL_DAT_NUM_DOC=3;                    //Numero del Documento.
    final int INT_TBL_DAT_FEC_DOC=4;                    //Fecha del documento.
    final int INT_TBL_DAT_NOM_CLI=5;                    //Nombre del Cliente.
    final int INT_TBL_DAT_CAN_PRO=6;                    //Cantidad.
    final int INT_TBL_DAT_PRE_UNI=7;                    //Precio Unitario.
    final int INT_TBL_DAT_POR_DES=8;                    //Porcentaje de descuento.
    
    
      //Variable
    private ZafParSis objParSis;
    private ZafUtil objUti;
    private ZafColNumerada objColNum;
    private ZafTblMod objTblMod;
    private ZafTblEdi objTblEdi;                        //Editor: Editor del JTable.
    
    
     private ZafMouMotAda objMouMotAda;                  //ToolTipText en TableHeader.
   // private ZafTblPopMnu objTblPopMnu;                  //PopupMenu: Establecer PeopuMenú en JTable.
    private Connection con;
    private Statement stm;
    private ResultSet rst;
    private String strSQL, strAux;
    private Vector vecDat, vecCab, vecReg;
    private Vector vecAux;
    private boolean blnCon;                             //true: Continua la ejecución del hilo.
    //Variables de la clase.
    private int intCodEmp;                              //Código de la empresa.
    private int intCodLoc;                              //Código del local.
    private int intCodTipDoc;                           //Código del tipo de documento.
    private int intCodMod;                              //Código del Movimiento.
    private String CodAlt;                               // Codigo Alternativo de Item
    private int CodCli;
    
    
    
    
    /** Creates new form ZafCom01_01 */
    public ZafCom01_01(java.awt.Frame parent, boolean modal, ZafParSis obj) {
        super(parent, modal);
        initComponents();
            //Inicializar objetos.
        objParSis=obj;
        if (!configurarFrm())
            exitForm();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanFrm = new javax.swing.JPanel();
        lblTit = new javax.swing.JLabel();
        tabFrm = new javax.swing.JTabbedPane();
        panGen = new javax.swing.JPanel();
        panGenCab = new javax.swing.JPanel();
        panGenDet = new javax.swing.JPanel();
        spnDat = new javax.swing.JScrollPane();
        tblDat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSqlUptCC = new javax.swing.JTextArea();
        panBar = new javax.swing.JPanel();
        panBot = new javax.swing.JPanel();
        butCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanFrm.setLayout(new java.awt.BorderLayout());

        lblTit.setFont(new java.awt.Font("MS Sans Serif", 1, 14)); // NOI18N
        lblTit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTit.setText("Título");
        PanFrm.add(lblTit, java.awt.BorderLayout.NORTH);

        panGen.setLayout(new java.awt.BorderLayout());

        panGenCab.setPreferredSize(new java.awt.Dimension(0, 24));
        panGenCab.setLayout(null);
        panGen.add(panGenCab, java.awt.BorderLayout.NORTH);

        panGenDet.setLayout(new java.awt.BorderLayout());

        tblDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnDat.setViewportView(tblDat);

        panGenDet.add(spnDat, java.awt.BorderLayout.CENTER);

        panGen.add(panGenDet, java.awt.BorderLayout.CENTER);

        tabFrm.addTab("General", panGen);

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtSqlUptCC.setColumns(20);
        txtSqlUptCC.setLineWrap(true);
        txtSqlUptCC.setRows(5);
        txtSqlUptCC.setText("/* CASO QUE COMPRA DE TUVAL A DOMULTI  PROBLEMAS IVA EN COMPRA */\nUPDATE tbm_detdia SET co_cta=584  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01'  \nand a1.co_cta= 2949\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n/* CASO QUE COMPRA DE TUVAL A DOMULTI */\nUPDATE tbm_detdia SET co_cta=733  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01'  \nand a1.co_cta= 2950\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n/* CASO QUE COMPRA DE CASTEK A TUVAL */\nUPDATE tbm_detdia SET co_cta=94  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01'  \nand a1.co_cta= 1250\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n/* CASO QUE COMPRA DE CASTEK A TUVAL */\nUPDATE tbm_detdia SET co_cta=154  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01'  \nand a1.co_cta= 1251\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\t\n\n/* CASO QUE COMPRA DE DIMULTI A CASTEK   */\nUPDATE tbm_detdia SET co_cta=545  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' \nand a1.co_cta= 2226\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n\n;\n/* CASO QUE COMPRA DE DIMULTI A CASTEK   */\nUPDATE tbm_detdia SET co_cta=688  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' \nand a1.co_cta= 2227\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n\n/********************************************************************************/\n\n;\n\n/* CASO QUE VENTA DE TUVAL A CASTEK */\nUPDATE tbm_detdia SET co_cta=2690  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=603  \nand a1.co_cta= 29\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n\n\n/* CASO QUE VENTA DE TUVAL A DIMULTI */\nUPDATE tbm_detdia SET co_cta=2691  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli= 1039  \nand a1.co_cta= 29\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n;\n/* CASO QUE COMPRA DE TUVAL A CASTEK */\nUPDATE tbm_detdia SET co_cta=2692  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=603  \nand a1.co_cta= 733\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n\n\n/* CASO QUE COMPRA DE TUVAL A DOMULTI */\nUPDATE tbm_detdia SET co_cta=2693  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=1 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=1039  \nand a1.co_cta= 733\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n\n\n\n/* CASO QUE VENTA DE CASTEK A TUVAL */\nUPDATE tbm_detdia SET co_cta=1186  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=2854  \nand a1.co_cta= 1156\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n\n/* CASO QUE VENTA DE CASTEK A TUVAL */\nUPDATE tbm_detdia SET co_cta=1186  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=2854  \nand a1.co_cta= 24\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n/* CASO QUE VENTA DE CASTEK A DIMULTI */\nUPDATE tbm_detdia SET co_cta=1187  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=789  \nand a1.co_cta= 24\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n;\n\n/* CASO QUE COMPRA DE CASTEK A TUVAL */\nUPDATE tbm_detdia SET co_cta=1188  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=2854  \nand a1.co_cta= 154\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n\n/* CASO QUE COMPRA DE CASTEK A DIMULTI */\nUPDATE tbm_detdia SET co_cta=1189  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=789  \nand a1.co_cta= 154\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n;\n\n\n/* CASO QUE VENTA DE DIMULTI A TUVAL */\nUPDATE tbm_detdia SET co_cta=2128  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=3117  \nand a1.co_cta= 28\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n/* CASO QUE VENTA DE DIMULTI A CASTEK   */\nUPDATE tbm_detdia SET co_cta=2129  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli=498  \nand a1.co_cta= 28\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n;\n\n\n/* CASO QUE COMPRA DE DIMULTI A TUVAL */\nUPDATE tbm_detdia SET co_cta=2130  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=3117  \nand a1.co_cta= 688\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n;\n/* CASO QUE COMPRA DE DIMULTI A CASTEK   */\nUPDATE tbm_detdia SET co_cta=2131  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=4 and a.co_loc=2 and a.co_tipdoc in (2,4) and a.fe_doc >= '2011-01-01' and a.co_cli=498  \nand a1.co_cta= 688\n) as x \n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n\n;\n\nUPDATE tbm_detdia SET co_cta= 545  FROM ( \n\nselect * from (\nselect a1.* from  tbm_cabmovinv as a \ninner join tbm_detdia as a1 on (a1.co_emp=a.co_emp and a1.co_loc=a.co_loc and a1.co_tipdoc=a.co_tipdoc and a1.co_dia=a.co_doc)\nwhere a.co_emp=2 and a.co_loc=5 and a.co_tipdoc in (1,3) and a.fe_doc >= '2011-01-01' and a.co_cli in ( 789 , 2854 )  \nand a1.co_cta in (1163, 1037 , 551 )\n) as x \n\n\n) AS x \nWHERE tbm_detdia.co_emp=x.co_emp and tbm_detdia.co_loc=x.co_loc and tbm_detdia.co_tipdoc=x.co_tipdoc and tbm_detdia.co_dia=x.co_dia and tbm_detdia.co_reg=x.co_reg\n\n\n;\nupdate tbm_pagmovinv set  tx_codsri='312' where co_emp=1 and co_loc=5 and co_tipdoc=1 and nd_porret != 0 and  fe_ven >= '2011-01-01' and tx_codsri is null\n\n;\nupdate tbm_pagmovinv set  tx_codsri='312' where co_emp=2 and co_loc=5 and co_tipdoc=1 and nd_porret != 0 and  fe_ven >= '2011-01-01' and tx_codsri is null\n\n;\nupdate tbm_pagmovinv set  tx_codsri='312' where co_emp=4 and co_loc=2 and co_tipdoc=1 and nd_porret != 0 and  fe_ven >= '2011-01-01' and tx_codsri is null\n\n\n\n\t");
        jScrollPane1.setViewportView(txtSqlUptCC);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabFrm.addTab("tab2", jPanel1);

        PanFrm.add(tabFrm, java.awt.BorderLayout.CENTER);

        panBar.setLayout(new java.awt.BorderLayout());

        panBot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        butCan.setText("Cancelar");
        butCan.setPreferredSize(new java.awt.Dimension(92, 25));
        butCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCanActionPerformed(evt);
            }
        });
        panBot.add(butCan);

        panBar.add(panBot, java.awt.BorderLayout.CENTER);

        PanFrm.add(panBar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanFrm, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-400)/2, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void butCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_butCanActionPerformed
    
   public void cargaTexto(String sql,int Codcli){
        strSQL = sql;
        CodCli = Codcli;
        cargarDetReg();
    }
    
       
    
    
    private void exitForm() 
    {
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanFrm;
    private javax.swing.JButton butCan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTit;
    private javax.swing.JPanel panBar;
    private javax.swing.JPanel panBot;
    private javax.swing.JPanel panGen;
    private javax.swing.JPanel panGenCab;
    private javax.swing.JPanel panGenDet;
    private javax.swing.JScrollPane spnDat;
    private javax.swing.JTabbedPane tabFrm;
    private javax.swing.JTable tblDat;
    private javax.swing.JTextArea txtSqlUptCC;
    // End of variables declaration//GEN-END:variables
     
       private boolean cargarDetReg()
    {
        boolean blnRes=true;
        try
        {
            
            intCodEmp=objParSis.getCodigoEmpresa();
            intCodLoc=objParSis.getCodigoLocal();
            con=DriverManager.getConnection(objParSis.getStringConexion(), objParSis.getUsuarioBaseDatos(), objParSis.getClaveBaseDatos());
            if (con!=null)
            {
                stm=con.createStatement();

                //Armar la sentencia SQL.

                
                rst=stm.executeQuery(strSQL);
                //Limpiar vector de datos.
                vecDat.clear();
                //Obtener los registros.
                while (rst.next())
                {
                    vecReg=new Vector();
                    vecReg.add(INT_TBL_DAT_LIN,"");
                    vecReg.add(INT_TBL_DAT_COD_DOC,rst.getString("co_doc"));
                    vecReg.add(INT_TBL_DAT_NUM_COT,rst.getString("ne_numcot"));
                    vecReg.add(INT_TBL_DAT_NUM_DOC,rst.getString("ne_numdoc"));
                    vecReg.add(INT_TBL_DAT_FEC_DOC,rst.getString("fe_doc"));
                    vecReg.add(INT_TBL_DAT_NOM_CLI,rst.getString("tx_nomcli"));
                    vecReg.add(INT_TBL_DAT_CAN_PRO,rst.getString("can"));
                    vecReg.add(INT_TBL_DAT_PRE_UNI,rst.getString("nd_cosuni"));
                    vecReg.add(INT_TBL_DAT_POR_DES,rst.getString("nd_pordes")+"%");
                    vecDat.add(vecReg);
                }
                rst.close();
                stm.close();
                con.close();
                rst=null;
                stm=null;
                con=null;
                //Asignar vectores al modelo.
                objTblMod.setData(vecDat);
                tblDat.setModel(objTblMod);
                vecDat.clear();
//                if (intNumTotReg==tblDat.getRowCount())
//                    lblMsgSis.setText("Se encontraron " + intNumTotReg + " registros.");
//                else
//                    lblMsgSis.setText("Se encontraron " + intNumTotReg + " registros pero sólo se procesaron " + tblDat.getRowCount() + ".");
//                pgrSis.setValue(0);
//                butCon.setText("Consultar");
            }
        }
        catch (java.sql.SQLException e)
        {
            blnRes=false;
            objUti.mostrarMsgErr_F1(this, e);
        }
        catch (Exception e)
        {
            blnRes=false;
            objUti.mostrarMsgErr_F1(this, e);
        }
        return blnRes;
    }
    
       
        
       /** Configurar el formulario. */
    private boolean configurarFrm()
    {
        boolean blnRes=true;
        try
        {
            //Inicializar objetos.
            objUti=new ZafUtil();
            strAux=objParSis.getNombreMenu();
            this.setTitle(strAux);
            lblTit.setText(strAux);
            //Configurar objetos.
//            txtCodTipDoc.setVisible(false);
            //Configurar JTable: Establecer el modelo.
            vecDat=new Vector();    //Almacena los datos
            vecCab=new Vector(8);   //Almacena las cabeceras
            vecCab.clear();
            vecCab.add(INT_TBL_DAT_LIN,"");
            vecCab.add(INT_TBL_DAT_COD_DOC,"Cód.Reg.");
            vecCab.add(INT_TBL_DAT_NUM_COT,"Núm.Cot.");
            vecCab.add(INT_TBL_DAT_NUM_DOC,"Núm.Doc.");
            vecCab.add(INT_TBL_DAT_FEC_DOC,"Fecha");
            vecCab.add(INT_TBL_DAT_NOM_CLI,"Cliente");
            vecCab.add(INT_TBL_DAT_CAN_PRO,"Cantidad");
            vecCab.add(INT_TBL_DAT_PRE_UNI,"Precio");
            vecCab.add(INT_TBL_DAT_POR_DES,"Desc");
            
            
            objTblMod=new ZafTblMod();
            objTblMod.setHeader(vecCab);
            tblDat.setModel(objTblMod);
            //Configurar JTable: Establecer tipo de selección.
             tblDat.setRowSelectionAllowed(true);
             tblDat.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            //Configurar JTable: Establecer la fila de cabecera.
            objColNum=new ZafColNumerada(tblDat,INT_TBL_DAT_LIN);
            //Configurar JTable: Establecer el menú de contexto.
//            objTblPopMnu=new ZafTblPopMnu(tblDat);
            //Configurar JTable: Establecer el tipo de redimensionamiento de las columnas.
            tblDat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            //Configurar JTable: Establecer el ancho de las columnas.
            javax.swing.table.TableColumnModel tcmAux=tblDat.getColumnModel();
            tcmAux.getColumn(INT_TBL_DAT_LIN).setPreferredWidth(30);
            tcmAux.getColumn(INT_TBL_DAT_NUM_COT).setPreferredWidth(70);
            tcmAux.getColumn(INT_TBL_DAT_NUM_DOC).setPreferredWidth(70);
            tcmAux.getColumn(INT_TBL_DAT_FEC_DOC).setPreferredWidth(80);
            tcmAux.getColumn(INT_TBL_DAT_NOM_CLI).setPreferredWidth(150);
            tcmAux.getColumn(INT_TBL_DAT_CAN_PRO).setPreferredWidth(60);
            tcmAux.getColumn(INT_TBL_DAT_PRE_UNI).setPreferredWidth(60);
            tcmAux.getColumn(INT_TBL_DAT_POR_DES).setPreferredWidth(50);
            
            tblDat.getTableHeader().setReorderingAllowed(false);
            //Configurar JTable: Ocultar columnas del sistema.
            tcmAux.getColumn(INT_TBL_DAT_COD_DOC).setWidth(0);
            tcmAux.getColumn(INT_TBL_DAT_COD_DOC).setMaxWidth(0);
            tcmAux.getColumn(INT_TBL_DAT_COD_DOC).setMinWidth(0);
            tcmAux.getColumn(INT_TBL_DAT_COD_DOC).setPreferredWidth(0);
            tcmAux.getColumn(INT_TBL_DAT_COD_DOC).setResizable(false);
            
        objMouMotAda=new ZafMouMotAda();
            tblDat.getTableHeader().addMouseMotionListener(objMouMotAda);
            //Configurar JTable: Establecer columnas editables.
            vecAux=new Vector();
            objTblMod.setColumnasEditables(vecAux);
            vecAux=null;
            //Configurar JTable: Editor de la tabla.
            objTblEdi=new ZafTblEdi(tblDat);

             objTblMod.setModoOperacion(objTblMod.INT_TBL_EDI);
            //Libero los objetos auxiliares.
            tcmAux=null;
        }
        catch(Exception e)
        {
            blnRes=false;
//            objUti.mostrarMsgErr_F1(this, e);
        }
        return blnRes;
    }
    
    
    
    
    
      private class ZafMouMotAda extends java.awt.event.MouseMotionAdapter
    {
        public void mouseMoved(java.awt.event.MouseEvent evt)
        {
            int intCol=tblDat.columnAtPoint(evt.getPoint());
            String strMsg="";
            switch (intCol)
            {
                case INT_TBL_DAT_LIN:
                    strMsg="";
                    break;
                    
                 case INT_TBL_DAT_NUM_COT:
                    strMsg="Número de cotización";
                    break;
                
                case INT_TBL_DAT_NUM_DOC:
                    strMsg="Número de documento";
                    break;
                    
                    
                case INT_TBL_DAT_FEC_DOC:
                    strMsg="Fecha del documento";
                    break;
                    
                case INT_TBL_DAT_NOM_CLI:
                    strMsg="Nombre del cliente";
                    break;    
                
                case INT_TBL_DAT_CAN_PRO:
                    strMsg="Cantidad ";
                    break;
                    
                case INT_TBL_DAT_PRE_UNI:
                    strMsg="Precio unitario";
                    break;    
                    
                 case INT_TBL_DAT_POR_DES:
                    strMsg="Porcentaje de descuento";
                    break; 

                default:
                    strMsg="";
                    break;
            }
            tblDat.getTableHeader().setToolTipText(strMsg);
        }
    }
    
    
}
