/*
 * ZafCxC79_01.java
 *
 * Created on Aug 17, 2010, 1:53:49 PM
 */
package CxC.ZafCxC79;
import Librerias.ZafParSis.ZafParSis;
import Librerias.ZafUtil.ZafUtil;

/**
 *
 * @author jayapata
 */
public class ZafCxC79_01 extends javax.swing.JDialog 
{
    ZafParSis objParSis;
    ZafUtil objUti;

    /**
     * Creates new form ZafCxC79_01
     */
    public ZafCxC79_01(java.awt.Frame parent, boolean modal, ZafParSis objParsis, double dblpag) 
    {
        super(parent, modal);
        try 
        {
            this.objParSis = (Librerias.ZafParSis.ZafParSis) objParsis.clone();
            initComponents();
            txtPag.setText("" + dblpag);
            this.setTitle("" + objParSis.getNombreMenu());
            objUti = new ZafUtil();
        } 
        catch (CloneNotSupportedException e) {     objUti.mostrarMsgErr_F1(this, e);      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JPanel();
        lblPag = new javax.swing.JLabel();
        txtPag = new javax.swing.JTextField();
        lblEfe = new javax.swing.JLabel();
        txtEfe = new javax.swing.JTextField();
        lblCam = new javax.swing.JLabel();
        txtCam = new javax.swing.JTextField();
        butCal = new javax.swing.JButton();
        butCer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pan1.setLayout(null);

        lblPag.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblPag.setText("Pago:");
        pan1.add(lblPag);
        lblPag.setBounds(10, 20, 50, 20);

        txtPag.setEditable(false);
        txtPag.setBackground(objParSis.getColorCamposSistema());
        pan1.add(txtPag);
        txtPag.setBounds(70, 20, 180, 20);

        lblEfe.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEfe.setText("Efectivo:");
        pan1.add(lblEfe);
        lblEfe.setBounds(10, 40, 50, 20);

        txtEfe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEfeKeyPressed(evt);
            }
        });
        pan1.add(txtEfe);
        txtEfe.setBounds(70, 40, 180, 20);

        lblCam.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCam.setText("Cambio:");
        pan1.add(lblCam);
        lblCam.setBounds(10, 60, 50, 20);

        txtCam.setEditable(false);
        txtCam.setBackground(objParSis.getColorCamposSistema());
        txtCam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pan1.add(txtCam);
        txtCam.setBounds(70, 60, 180, 30);

        butCal.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        butCal.setText("Calcular");
        butCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalActionPerformed(evt);
            }
        });
        pan1.add(butCal);
        butCal.setBounds(30, 100, 100, 23);

        butCer.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        butCer.setText("Cerrar");
        butCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCerActionPerformed(evt);
            }
        });
        pan1.add(butCer);
        butCer.setBounds(140, 100, 110, 23);

        getContentPane().add(pan1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(279, 180));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butCerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCerActionPerformed
        this.dispose();

    }//GEN-LAST:event_butCerActionPerformed

    private void butCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalActionPerformed
        calcular();
    }//GEN-LAST:event_butCalActionPerformed

    private void txtEfeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfeKeyPressed
        if (java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()) {
            calcular();
        }
    }//GEN-LAST:event_txtEfeKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCal;
    private javax.swing.JButton butCer;
    private javax.swing.JLabel lblCam;
    private javax.swing.JLabel lblEfe;
    private javax.swing.JLabel lblPag;
    private javax.swing.JPanel pan1;
    private javax.swing.JTextField txtCam;
    private javax.swing.JTextField txtEfe;
    private javax.swing.JTextField txtPag;
    // End of variables declaration//GEN-END:variables

    
    private void MensajeInf(String strMensaje) 
    {
        javax.swing.JOptionPane obj = new javax.swing.JOptionPane();
        String strTit;
        strTit = "Mensaje del sistema Zafiro";
        obj.showMessageDialog(this, strMensaje, strTit, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void calcular() 
    {
        try 
        {
            double dblPag = objUti.redondear(txtPag.getText(), 2);
            double dblEfe = objUti.redondear((txtEfe.getText().equals("") ? "0" : txtEfe.getText()), 2);
            double dblCam = dblPag - dblEfe;

            if (dblCam > 0) 
            {
                txtCam.setText("-Error-");
                MensajeInf("EL VALOR INGRESADO NO PUEDE SER MENOR AL PAGO");
            }
            else
            {
                txtCam.setText("" + objUti.redondear(dblCam, 2) * -1);
            }

        }
        catch (Exception evt) {    objUti.mostrarMsgErr_F1(this, evt);     }
    }


}
