/*
 *
 * Created on 9 de marzo de 2006, 9:12
 *
 * v0.1 
 */

package Ventas.ZafVen31;

import Librerias.ZafParSis.ZafParSis;
import Librerias.ZafUtil.ZafUtil;
/**
 *
 * @author  Javier Ayapata
 */
public class ZafVen31_01 extends javax.swing.JDialog {
    //Variable
    private ZafParSis objParSis;
    private ZafUtil objUti;
    private String strObs, strObsIni;

    
      
     public ZafVen31_01(java.awt.Frame parent, boolean modal, ZafParSis obj) {
        super(parent, modal);
        initComponents();
        //Inicializar objetos.
        objParSis=obj;
        strObs="";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanFrm = new javax.swing.JPanel();
        lblTit = new javax.swing.JLabel();
        tabFrm = new javax.swing.JTabbedPane();
        panGen = new javax.swing.JPanel();
        panObs = new javax.swing.JPanel();
        spnDat = new javax.swing.JScrollPane();
        txtPanObs = new javax.swing.JTextPane();
        panBar = new javax.swing.JPanel();
        panBot = new javax.swing.JPanel();
        panBotExe = new javax.swing.JPanel();
        butAce = new javax.swing.JButton();
        butCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanFrm.setLayout(new java.awt.BorderLayout());

        lblTit.setFont(new java.awt.Font("MS Sans Serif", 1, 14));
        lblTit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTit.setText("Título");
        PanFrm.add(lblTit, java.awt.BorderLayout.NORTH);

        panGen.setLayout(new java.awt.BorderLayout());

        panObs.setPreferredSize(new java.awt.Dimension(9, 120));
        panObs.setLayout(new java.awt.BorderLayout());

        spnDat.setViewportView(txtPanObs);

        panObs.add(spnDat, java.awt.BorderLayout.CENTER);

        panGen.add(panObs, java.awt.BorderLayout.CENTER);

        tabFrm.addTab("General", panGen);

        PanFrm.add(tabFrm, java.awt.BorderLayout.CENTER);

        panBar.setLayout(new java.awt.BorderLayout());

        panBot.setLayout(new java.awt.BorderLayout());

        butAce.setMnemonic('A');
        butAce.setText("Aceptar");
        butAce.setPreferredSize(new java.awt.Dimension(92, 25));
        butAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceActionPerformed(evt);
            }
        });
        panBotExe.add(butAce);

        butCan.setMnemonic('C');
        butCan.setText("Cancelar");
        butCan.setToolTipText("Si presiona cancelar se borrará lo que ha ingresado");
        butCan.setPreferredSize(new java.awt.Dimension(92, 25));
        butCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCanActionPerformed(evt);
            }
        });
        panBotExe.add(butCan);

        panBot.add(panBotExe, java.awt.BorderLayout.EAST);

        panBar.add(panBot, java.awt.BorderLayout.CENTER);

        PanFrm.add(panBar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanFrm, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-400)/2, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        txtPanObs.setText("");
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void butAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceActionPerformed
        // TODO add your handling code here:        
        strObs=txtPanObs.getText();
        dispose();
    }//GEN-LAST:event_butAceActionPerformed

    private void butCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCanActionPerformed
        // TODO add your handling code here:
        strObs=strObsIni;
        dispose();
    }//GEN-LAST:event_butCanActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanFrm;
    private javax.swing.JButton butAce;
    private javax.swing.JButton butCan;
    private javax.swing.JLabel lblTit;
    private javax.swing.JPanel panBar;
    private javax.swing.JPanel panBot;
    private javax.swing.JPanel panBotExe;
    private javax.swing.JPanel panGen;
    private javax.swing.JPanel panObs;
    private javax.swing.JScrollPane spnDat;
    private javax.swing.JTabbedPane tabFrm;
    private javax.swing.JTextPane txtPanObs;
    // End of variables declaration//GEN-END:variables
       

    
    /** Cerrar la aplicacián. */
    private void exitForm(){
        dispose();
    }    
    

    
    public String getContenido(){
        return strObs;
    }


    public void setContenido(String observacion, String editable){
        txtPanObs.setText(observacion);
        if(editable.equals("S")){
            txtPanObs.setEditable(false);
        }
        else{
            txtPanObs.setEditable(true);
        }
        strObsIni=observacion;
    }
    
    
}
