/*
 * ZafCon47_01.java
 *
 * Created on 8 de agosto de 2007, 03:28 PM
 */

package Contabilidad.ZafCon47;

import Librerias.ZafParSis.ZafParSis;
import Librerias.ZafUtil.ZafUtil;

/**
 *    
 * @author  jayapata     
 */
public class ZafCon47_02 extends javax.swing.JDialog {
    
     private ZafParSis objParSis;
     javax.swing.JDialog jfrThis; //Hace referencia a this
     
   
     Librerias.ZafParSis.ZafParSis objZafParSis;
     ZafUtil objUti;
     String strCodMay="",strMay="",strCodDet="",strDet="";
     
     public boolean blnAcepta = false;
     public boolean blnEst=false;
     private String Str_RegSel[];
      
      
    /** Creates new form ZafCon47_01 */
    public ZafCon47_02(java.awt.Frame parent, boolean modal, ZafParSis obj) {
        super(parent, modal);
        try{
            objUti = new ZafUtil();
            initComponents(); 
            this.objZafParSis = (Librerias.ZafParSis.ZafParSis) obj.clone();
        }catch (Exception e){  objUti.mostrarMsgErr_F1(this, e);
        }
    }
    
      
    
     public void Configura_ventana_consulta(){
       
        
       
     }
    
     
     
    
     
       
    
    
    
    /** This method is called from within the constructor to 
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        optFil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        PanBut = new javax.swing.JPanel();
        panBut2 = new javax.swing.JPanel();
        ButAce = new javax.swing.JButton();
        ButCan = new javax.swing.JButton();
        TabGen = new javax.swing.JTabbedPane();
        PanGen = new javax.swing.JPanel();
        optGrp = new javax.swing.JRadioButton();
        optMay = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanBut.setLayout(new java.awt.BorderLayout());

        ButAce.setText("Aceptar");
        ButAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAceActionPerformed(evt);
            }
        });

        panBut2.add(ButAce);

        ButCan.setText("Cancelar");
        ButCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCanActionPerformed(evt);
            }
        });

        panBut2.add(ButCan);

        PanBut.add(panBut2, java.awt.BorderLayout.EAST);

        jPanel1.add(PanBut, java.awt.BorderLayout.SOUTH);

        PanGen.setLayout(null);

        optGrp.setSelected(true);
        optGrp.setText("Eliminar Bloque");
        optFil.add(optGrp);
        optGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optGrpActionPerformed(evt);
            }
        });

        PanGen.add(optGrp);
        optGrp.setBounds(20, 28, 180, 20);

        optMay.setText("Eliminar solo la fila. ");
        optFil.add(optMay);
        optMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMayActionPerformed(evt);
            }
        });

        PanGen.add(optMay);
        optMay.setBounds(20, 56, 196, 20);

        TabGen.addTab("General", PanGen);

        jPanel1.add(TabGen, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-389)/2, (screenSize.height-224)/2, 389, 224);
    }//GEN-END:initComponents

    private void optMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMayActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_optMayActionPerformed

    private void optGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optGrpActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_optGrpActionPerformed

    
    
    
    
     
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Configura_ventana_consulta();
    }//GEN-LAST:event_formWindowOpened

    private void ButAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAceActionPerformed
        // TODO add your handling code here:
         
         
           blnEst=true; salir(); 
         
         
          
    }//GEN-LAST:event_ButAceActionPerformed

    
     public boolean acepta(){
        return blnEst;
    }
     
    
     
     
     
      public String GetCamSel(int Idx){
        if(!(Str_RegSel==null)){
            if(Idx <= 0 || Idx > Str_RegSel.length)
                return "El parametro debe ser entre 1 y " + Integer.toString(Str_RegSel.length) ;
            else
                return Str_RegSel[Idx-1];
        }else{
            return "";
        }
    }
      
        
      
      
      
     private void salir(){
               Str_RegSel = new String[1];
              
               if(optGrp.isSelected()){
                  Str_RegSel[0] =  "1";
                
               }
               if(optMay.isSelected()){
                   Str_RegSel[0] = "2";
               }
              
                      
               blnAcepta = true;
                      
         dispose();
    }
     
     
     
     
     
     
    
    
     
     
    
   
    
    
        
    
    private void MensajeInf(String strMensaje){
            javax.swing.JOptionPane obj =new javax.swing.JOptionPane();
            String strTit;
            strTit="Mensaje del sistema Zafiro";
            obj.showMessageDialog(jfrThis,strMensaje,strTit,javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    
    
    private void ButCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCanActionPerformed
        // TODO add your handling code here:
         dispose();     
    }//GEN-LAST:event_ButCanActionPerformed
            
    /**     
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAce;
    private javax.swing.JButton ButCan;
    private javax.swing.JPanel PanBut;
    private javax.swing.JPanel PanGen;
    private javax.swing.JTabbedPane TabGen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup optFil;
    private javax.swing.JRadioButton optGrp;
    private javax.swing.JRadioButton optMay;
    private javax.swing.JPanel panBut2;
    // End of variables declaration//GEN-END:variables
    
}
